#!/bin/bash

set -u

FLAG="/run/vt320-enter"

rm -f "$FLAG"

# Asegurarnos de que Plymouth está visible
/usr/bin/plymouth show-splash || true

# ------------------------------------------------------------
# Avisar al tema Plymouth que el sistema está listo
# ------------------------------------------------------------

/usr/bin/plymouth display-message \
    --text="__VT320_READY__"


# ------------------------------------------------------------
# Esperar ENTER
#
# Plymouth recibe la tecla y ejecuta touch.
# \n corresponde a Enter.
# ------------------------------------------------------------

/usr/bin/plymouth watch-keystroke \
    --keys=$'\n' \
    --command="/usr/bin/touch $FLAG"


# ------------------------------------------------------------
# Esperar por seguridad
# ------------------------------------------------------------

while [ ! -f "$FLAG" ]; do
    sleep 0.05
done


# ------------------------------------------------------------
# Continuar con el sistema
# ------------------------------------------------------------

/usr/bin/plymouth quit